# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Delete old workflow run

on:
  workflow_dispatch:

  repository_dispatch:
    types: [Delete-old-workflow-run]

jobs:
  Delete-old-workflow-run:
    name: Delete old workflow run
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow run [BnqDzj/FFmpeg-Builds-nonfree]
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.PAT}}
          repository: BnqDzj/FFmpeg-Builds-nonfree
          retain_days: 0
          keep_minimum_runs: 0

      - name: Delete old workflow run [BnqDzj/Cloud189Checkin]
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.PAT}}
          repository: BnqDzj/Cloud189Checkin
          retain_days: 0
          keep_minimum_runs: 0
