# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Repo Sync

on:
  workflow_dispatch:

  repository_dispatch:
    types: [Repo-Sync]

jobs:
  Repo-Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BsBlog/alist
        uses: actions/checkout@main
        with:
          repository: BsBlog/alist
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: BsBlog/alist
          fetch-depth: 0

      - name: Add upstream
        run: |
          cd ${{ github.workspace }}/BsBlog/alist
          git remote add upstream https://github.com/alistgo/alist.git
          git fetch upstream

      - name: Reset to upstream/main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          for branch in $(git branch -r | grep '^upstream/' | sed 's/upstream\///'); do
            git checkout $branch
            git reset --hard upstream/$branch
            git push origin $branch --force
          done

      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
